In [13]:
import numpy as np

In [14]:
a = [1,2,3,4]
b = [2,3,4,5]

In [15]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
# Array numpy kütüphanesinin bir veri tipidir. Liste metodunda birer birer tutulan sayıları toplu bir şekilde tutup veri tutma maliyetini azaltır.

In [16]:
a * b 
# Karmaşık işlemleri daha kolay hale getirdi.

array([ 2,  6, 12, 20])

In [8]:
# Sıfırdan Array oluşturma

In [9]:
import numpy as np

In [17]:
np.zeros(7, dtype = int)
# dtype default olarak float olan tipi başka bir tipe tanımlamamızı sağlar.

array([0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((8,8), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
np.arange(0,99, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.random.normal(10,12,(3,4))

array([[ 12.67410853, -11.49291274,  29.4859397 ,  14.00716345],
       [  6.0377927 ,  37.65064107,  14.10768656,  -1.53407553],
       [ 24.35211198,  10.76324471,  18.54850998, -16.89111355]])

In [26]:
np.random.randint(0,10,(3,5))

array([[4, 6, 4, 6, 0],
       [1, 5, 2, 5, 6],
       [5, 8, 6, 2, 0]])

# ÖZELLİKLER

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam veri sayısı
* **dtype**: array veri tipi

In [36]:
a = np.random.randint(10, size = 10)

In [37]:
a.ndim

1

In [38]:
a.shape

(10,)

In [39]:
a.size

10

In [40]:
a.dtype

dtype('int32')

In [42]:
b = np.random.randint(8, size = (3,4))

In [43]:
b.ndim

2

In [44]:
b.shape

(3, 4)

In [45]:
b.size

12

In [46]:
b.dtype

dtype('int32')

# Yeniden Şeklillendirme(reshaping)

In [47]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a = np.arange(1,10)

In [51]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.ndim

1

In [53]:
b = a.reshape((1,9))

In [54]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
b.ndim

2