# Pandas Serisi Oluşturmak

In [3]:
import pandas as pd

In [8]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [5]:
seri = pd.Series([10,88,3,4,5])

In [6]:
type(seri)

pandas.core.series.Series

In [9]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
seri.dtype

dtype('int64')

In [11]:
seri.size

5

In [12]:
seri.ndim

1

In [13]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [14]:
seri.head(3)
#baştan setlere bakar.

0    10
1    88
2     3
dtype: int64

In [15]:
seri.tail(3)
#sondan setlere bakar.

2    3
3    4
4    5
dtype: int64

In [ ]:
 # index isimlendirmeleri

In [17]:
pd.Series([15,245,331242,92134,1125])

0        15
1       245
2    331242
3     92134
4      1125
dtype: int64

In [20]:
pd.Series([15,245,331242,92134,1125], index = [10,11,12,13,14])
# indexleri isimlendirdik, sadece numerik değil string ifadelerle de isimlendirilebilir.

10        15
11       245
12    331242
13     92134
14      1125
dtype: int64

In [26]:
seri = pd.Series([15,245,331242,92134,1125], index = ["a","b","c","d","e"])
pd.Series([15,245,331242,92134,1125], index = ["a","b","c","d","e"])

a        15
b       245
c    331242
d     92134
e      1125
dtype: int64

In [25]:
seri["a":"c"]

a        15
b       245
c    331242
dtype: int64

In [ ]:
#sözlük üzerinden liste oluşturmak

In [27]:
sozluk = {"reg":10, "log":11,"cart":12}

In [28]:
seri = pd.Series(sozluk)

In [29]:
seri

reg     10
log     11
cart    12
dtype: int64

In [ ]:
# iki seriyi birleştirerek seri oluşturma

In [30]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman işlemleri

In [31]:
import numpy as np

In [32]:
a = np.array([412,1231,5346,6242,121])

In [35]:
seri = pd.Series(a)
seri

0     412
1    1231
2    5346
3    6242
4     121
dtype: int32

In [36]:
seri[0]

412

In [37]:
seri[0:2]

0     412
1    1231
dtype: int32

In [40]:
seri = pd.Series([218213,124141,213127,7921235], 
                 index = ["reg","loj","cart","rf"])
seri

reg      218213
loj      124141
cart     213127
rf      7921235
dtype: int64

In [41]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [42]:
seri.keys

<bound method Series.keys of reg      218213
loj      124141
cart     213127
rf      7921235
dtype: int64>

In [43]:
list(seri.items())

[('reg', 218213), ('loj', 124141), ('cart', 213127), ('rf', 7921235)]

In [44]:
seri.values

array([ 218213,  124141,  213127, 7921235], dtype=int64)

In [ ]:
#eleman sorgulama

In [45]:
"reg" in seri

True

In [46]:
seri["reg"]

218213

In [47]:
seri[["rf","reg"]]

rf     7921235
reg     218213
dtype: int64

In [48]:
seri["rf"] = 120
seri

reg     218213
loj     124141
cart    213127
rf         120
dtype: int64

# Pandas ile DataFrame Oluşturma

In [49]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [51]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2              3
3              4
4              5

In [54]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
#df isimlendirme

In [58]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [59]:
df.columns 

Index(['var1', 'var2', 'var3'], dtype='object')

In [60]:
df.columns = ("deg1","deg2","deg3")
df.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [61]:
type(df)

pandas.core.frame.DataFrame

In [62]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [63]:
df.shape

(3, 3)

In [64]:
df.ndim

2

In [65]:
df.size

9

In [66]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
type(df.values)

numpy.ndarray

In [68]:
df.head(1)

deg1  deg2  deg3
0     1     2     3

In [69]:
df.tail(2)

deg1  deg2  deg3
1     4     5     6
2     7     8     9

In [70]:
a = np.array([1,2,3,4,5])

In [71]:
pd.DataFrame(a,columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [91]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [92]:
sozluk = {"var1": s1, "var2": s2, "var3":s3}

In [93]:
sozluk

{'var1': array([9, 1, 1, 5, 7]),
 'var2': array([0, 4, 6, 4, 4]),
 'var3': array([9, 8, 6, 2, 0])}

In [94]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     9     0     9
1     1     4     8
2     1     6     6
3     5     4     2
4     7     4     0

In [77]:
df[0:1]

var1  var2  var3
0     2     0     2

In [78]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [95]:
df.index = ["a","b","c","d","e"] 
df

var1  var2  var3
a     9     0     9
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [85]:
#silme

In [96]:
df.drop("a", axis = 0)

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [86]:
df
# veri setinin ana yapısı üzerinde değişiklik olmaz

var1  var2  var3
a     2     0     2
b     2     9     9
c     7     7     1
d     9     2     4
e     1     2     4

In [97]:
df.drop("a", axis = 0, inplace = True)
df

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [ ]:
# inplace komutu kalıcı olarak siler

In [98]:
#fancy

In [99]:
l = ["c","e"]

In [100]:
df.drop(l, axis = 0)

var1  var2  var3
b     1     4     8
d     5     4     2

In [101]:
# degiskenler için

In [102]:
"var1" in df

True

In [103]:
l = ["var1","var4","var2"]

In [104]:
for i in l:
    print(i in df)

True
False
True


In [105]:
df

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [109]:
df["var4"] = df["var1"] * df["var2"]
df

var1  var2  var3  var4
b     1     4     8     4
c     1     6     6     6
d     5     4     2    20
e     7     4     0    28

In [110]:
#degisken silme 

In [111]:
df.drop("var4", axis = 1)

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [112]:
df.drop("var4", axis = 1, inplace = True)
df

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [114]:
l = ["var1","var2"]

In [115]:
df.drop(l, axis = 1)

var3
b     8
c     6
d     2
e     0