# Pandas Serisi Oluşturmak

In [3]:
import pandas as pd

In [8]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [5]:
seri = pd.Series([10,88,3,4,5])

In [6]:
type(seri)

pandas.core.series.Series

In [9]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
seri.dtype

dtype('int64')

In [11]:
seri.size

5

In [12]:
seri.ndim

1

In [13]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [14]:
seri.head(3)
#baştan setlere bakar.

0    10
1    88
2     3
dtype: int64

In [15]:
seri.tail(3)
#sondan setlere bakar.

2    3
3    4
4    5
dtype: int64

In [ ]:
 # index isimlendirmeleri

In [17]:
pd.Series([15,245,331242,92134,1125])

0        15
1       245
2    331242
3     92134
4      1125
dtype: int64

In [20]:
pd.Series([15,245,331242,92134,1125], index = [10,11,12,13,14])
# indexleri isimlendirdik, sadece numerik değil string ifadelerle de isimlendirilebilir.

10        15
11       245
12    331242
13     92134
14      1125
dtype: int64

In [26]:
seri = pd.Series([15,245,331242,92134,1125], index = ["a","b","c","d","e"])
pd.Series([15,245,331242,92134,1125], index = ["a","b","c","d","e"])

a        15
b       245
c    331242
d     92134
e      1125
dtype: int64

In [25]:
seri["a":"c"]

a        15
b       245
c    331242
dtype: int64

In [ ]:
#sözlük üzerinden liste oluşturmak

In [27]:
sozluk = {"reg":10, "log":11,"cart":12}

In [28]:
seri = pd.Series(sozluk)

In [29]:
seri

reg     10
log     11
cart    12
dtype: int64

In [ ]:
# iki seriyi birleştirerek seri oluşturma

In [30]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman işlemleri

In [4]:
import numpy as np

In [32]:
a = np.array([412,1231,5346,6242,121])

In [35]:
seri = pd.Series(a)
seri

0     412
1    1231
2    5346
3    6242
4     121
dtype: int32

In [36]:
seri[0]

412

In [37]:
seri[0:2]

0     412
1    1231
dtype: int32

In [40]:
seri = pd.Series([218213,124141,213127,7921235], 
                 index = ["reg","loj","cart","rf"])
seri

reg      218213
loj      124141
cart     213127
rf      7921235
dtype: int64

In [41]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [42]:
seri.keys

<bound method Series.keys of reg      218213
loj      124141
cart     213127
rf      7921235
dtype: int64>

In [43]:
list(seri.items())

[('reg', 218213), ('loj', 124141), ('cart', 213127), ('rf', 7921235)]

In [44]:
seri.values

array([ 218213,  124141,  213127, 7921235], dtype=int64)

In [ ]:
#eleman sorgulama

In [45]:
"reg" in seri

True

In [46]:
seri["reg"]

218213

In [47]:
seri[["rf","reg"]]

rf     7921235
reg     218213
dtype: int64

In [48]:
seri["rf"] = 120
seri

reg     218213
loj     124141
cart    213127
rf         120
dtype: int64

# Pandas ile DataFrame Oluşturma

In [49]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [51]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2              3
3              4
4              5

In [54]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
#df isimlendirme

In [58]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [59]:
df.columns 

Index(['var1', 'var2', 'var3'], dtype='object')

In [60]:
df.columns = ("deg1","deg2","deg3")
df.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [61]:
type(df)

pandas.core.frame.DataFrame

In [62]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [63]:
df.shape

(3, 3)

In [64]:
df.ndim

2

In [65]:
df.size

9

In [66]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
type(df.values)

numpy.ndarray

In [68]:
df.head(1)

deg1  deg2  deg3
0     1     2     3

In [69]:
df.tail(2)

deg1  deg2  deg3
1     4     5     6
2     7     8     9

In [70]:
a = np.array([1,2,3,4,5])

In [71]:
pd.DataFrame(a,columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [5]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [6]:
sozluk = {"var1": s1, "var2": s2, "var3":s3}

In [7]:
sozluk

{'var1': array([3, 1, 5, 8, 5]),
 'var2': array([5, 9, 0, 8, 1]),
 'var3': array([5, 8, 9, 7, 0])}

In [10]:
import pandas as pd
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     3     5     5
1     1     9     8
2     5     0     9
3     8     8     7
4     5     1     0

In [77]:
df[0:1]

var1  var2  var3
0     2     0     2

In [78]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
df.index = ["a","b","c","d","e"] 
df

var1  var2  var3
a     3     5     5
b     1     9     8
c     5     0     9
d     8     8     7
e     5     1     0

In [85]:
#silme

In [96]:
df.drop("a", axis = 0)

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [86]:
df
# veri setinin ana yapısı üzerinde değişiklik olmaz

var1  var2  var3
a     2     0     2
b     2     9     9
c     7     7     1
d     9     2     4
e     1     2     4

In [12]:
df.drop("a", axis = 0, inplace = True)
df

var1  var2  var3
b     1     9     8
c     5     0     9
d     8     8     7
e     5     1     0

In [ ]:
# inplace komutu kalıcı olarak siler

In [98]:
#fancy

In [13]:
l = ["c","e"]

In [14]:
df.drop(l, axis = 0)

var1  var2  var3
b     1     9     8
d     8     8     7

In [101]:
# degiskenler için

In [15]:
"var1" in df

True

In [16]:
l = ["var1","var4","var2"]

In [17]:
for i in l:
    print(i in df)

True
False
True


In [105]:
df

var1  var2  var3
b     1     4     8
c     1     6     6
d     5     4     2
e     7     4     0

In [18]:
df["var4"] = df["var1"] * df["var2"]
df

var1  var2  var3  var4
b     1     9     8     9
c     5     0     9     0
d     8     8     7    64
e     5     1     0     5

In [110]:
#degisken silme 

In [19]:
df.drop("var4", axis = 1)

var1  var2  var3
b     1     9     8
c     5     0     9
d     8     8     7
e     5     1     0

In [20]:
df.drop("var4", axis = 1, inplace = True)
df

var1  var2  var3
b     1     9     8
c     5     0     9
d     8     8     7
e     5     1     0

In [21]:
l = ["var1","var2"]

In [22]:
df.drop(l, axis = 1)

var3
b     8
c     9
d     7
e     0

# Birleştirme(Join) İşlemleri

In [61]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    25     1    21
1    29    26    26
2    15    23     1
3    28     7     2
4    14    10     5

In [46]:
df2 = df1 + 99

In [47]:
df2

var1  var2  var3
0   108   118   122
1   124   103   108
2   111   115   111
3   128   116   109
4   117   100   107

In [48]:
pd.concat([df1,df2])

var1  var2  var3
0     9    19    23
1    25     4     9
2    12    16    12
3    29    17    10
4    18     1     8
0   108   118   122
1   124   103   108
2   111   115   111
3   128   116   109
4   117   100   107

In [29]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[Hashable, NDFrame]',
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, defa

In [49]:
pd.concat([df1,df2], ignore_index = True)

var1  var2  var3
0     9    19    23
1    25     4     9
2    12    16    12
3    29    17    10
4    18     1     8
5   108   118   122
6   124   103   108
7   111   115   111
8   128   116   109
9   117   100   107

In [36]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [37]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [62]:
df2.columns = ["var1","var2","deg1"]

In [56]:
pd.concat([df1, df2], join = "inner", ignore_index = True)

var1  var2
0    17     7
1     8    14
2    25    28
3    23    26
4     9    11
5   108   118
6   124   103
7   111   115
8   128   116
9   117   100

# İleri Birleştirme İşlemleri

In [ ]:
# birebir birleştirme

In [67]:
df1 = pd.DataFrame({'calisanlar':['Ali','Veli','Ayse','Fatma'],
                    'grup':['Muhasebe','Muhendislik','Muhendislik','IK']})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [66]:
df2 = pd.DataFrame({'calisanlar':['Ayse','Ali','Veli','Fatma'],
                    'ilk_giris':[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [68]:
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [69]:
pd.merge(df1,df2, on = "calisanlar")
# merge komutu nereden birleştireceğini kendisi anlar fakat
# biz on komutu ile nerde birleştirileceğini belirleyebiliyoruz.

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [70]:
# coktan teke

In [71]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [74]:
df4 = pd.DataFrame({'grup': ['Muhasebe','Muhendislik','IK'],
                   'mudur': ['Caner','Mustafa','Berkcan']})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [75]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

In [76]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                             'Muhendislik','Muhendislik','IK','IK'],
                    'yetenekler': ['matematik','excel','kodlama',
                                   'linux','excel','yonetim']})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [82]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim