In [13]:
import numpy as np

In [14]:
a = [1,2,3,4]
b = [2,3,4,5]

In [15]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
# Array numpy kütüphanesinin bir veri tipidir. Liste metodunda birer birer tutulan sayıları toplu bir şekilde tutup veri tutma maliyetini azaltır.

In [16]:
a * b 
# Karmaşık işlemleri daha kolay hale getirdi.

array([ 2,  6, 12, 20])

In [8]:
# Sıfırdan Array oluşturma

In [9]:
import numpy as np

In [17]:
np.zeros(7, dtype = int)
# dtype default olarak float olan tipi başka bir tipe tanımlamamızı sağlar.

array([0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((8,8), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
np.arange(0,99, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.random.normal(10,12,(3,4))

array([[ 12.67410853, -11.49291274,  29.4859397 ,  14.00716345],
       [  6.0377927 ,  37.65064107,  14.10768656,  -1.53407553],
       [ 24.35211198,  10.76324471,  18.54850998, -16.89111355]])

In [26]:
np.random.randint(0,10,(3,5))

array([[4, 6, 4, 6, 0],
       [1, 5, 2, 5, 6],
       [5, 8, 6, 2, 0]])

# ÖZELLİKLER

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam veri sayısı
* **dtype**: array veri tipi

In [36]:
a = np.random.randint(10, size = 10)

In [37]:
a.ndim

1

In [38]:
a.shape

(10,)

In [39]:
a.size

10

In [40]:
a.dtype

dtype('int32')

In [42]:
b = np.random.randint(8, size = (3,4))

In [43]:
b.ndim

2

In [44]:
b.shape

(3, 4)

In [45]:
b.size

12

In [46]:
b.dtype

dtype('int32')

# Yeniden Şeklillendirme(reshaping)

In [47]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a = np.arange(1,10)

In [51]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.ndim

1

In [53]:
b = a.reshape((1,9))

In [54]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
b.ndim

2

# Array Birleştirme(Concatenation)

In [1]:
import numpy as np

In [7]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
y = np.array([4,5,6])

In [5]:
z = np.array([7,8,9])

In [8]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = ([[1,2,3],
     [4,5,6]])

In [10]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
np.concatenate([a,a], axis = 1)
# Satır, sütun bazında birleştime yapmak için axis argümanı kullanılır.
# 0 satırları 1 sütünları ifade eder.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array ayırma(Splitting)

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3,99,99,3,2,1])

In [15]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [16]:
a,b,c = np.split(x, [3,5])

In [17]:
a

array([1, 2, 3])

In [18]:
b

array([99, 99])

In [19]:
c

array([3, 2, 1])

In [ ]:
# iki boyutlu ayırma

In [21]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [23]:
ust, alt = np.vsplit(m, [2])

In [24]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [27]:
sag, sol = np.hsplit(m, [2])

In [28]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [29]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama(Sorting)

In [30]:
v = np.array([1,8,5,9,6,8,1,5,5,1])
v

array([1, 8, 5, 9, 6, 8, 1, 5, 5, 1])

In [31]:
np.sort(v)

array([1, 1, 1, 5, 5, 5, 6, 8, 8, 9])

In [34]:
v.sort()
# Bu sort fonksiyonu veri setinin formunu değiştirdi. 

In [33]:
v

array([1, 1, 1, 5, 5, 5, 6, 8, 8, 9])

In [ ]:
# Hatırlatma 
# np.random.normal(ortalama,standart sapma, matris)

In [35]:
m = np.random.normal(20,5, (3,3))
m

array([[22.98932603,  4.13480729, 22.20290731],
       [18.18283546, 18.47485415, 18.60106059],
       [14.349352  , 24.29221866, 14.42014766]])

In [36]:
np.sort(m, axis = 1)

array([[ 4.13480729, 22.20290731, 22.98932603],
       [18.18283546, 18.47485415, 18.60106059],
       [14.349352  , 14.42014766, 24.29221866]])

In [37]:
np.sort(m, axis = 0)

array([[14.349352  ,  4.13480729, 14.42014766],
       [18.18283546, 18.47485415, 18.60106059],
       [22.98932603, 24.29221866, 22.20290731]])

# İndex ile elemanlara erişmek

In [38]:
a = np.random.randint(10, size = 10)
a

array([6, 0, 4, 3, 9, 7, 3, 2, 9, 4])

In [39]:
a[0]

6

In [40]:
a[-1]

4

In [45]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 0, 3, 8, 7],
       [1, 1, 2, 9, 7],
       [5, 8, 9, 2, 1]])

In [46]:
m[1]

array([1, 1, 2, 9, 7])

In [47]:
m[1,1]

1

In [48]:
m[1,4] = 55

In [49]:
m

array([[ 6,  0,  3,  8,  7],
       [ 1,  1,  2,  9, 55],
       [ 5,  8,  9,  2,  1]])

In [52]:
m[1,3] = 2.2

In [54]:
m

array([[ 6,  0,  3,  8,  7],
       [ 1,  1,  2,  2, 55],
       [ 5,  8,  9,  2,  1]])

# Sciling ile Elemanlara Erişmek

In [55]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
a[0:3]

array([20, 21, 22])

In [57]:
a[1::2]

array([21, 23, 25, 27, 29])

In [ ]:
# iki boyutlu slice işlemleri

In [60]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 6, 1, 4, 2],
       [4, 1, 4, 5, 9],
       [5, 2, 5, 9, 8],
       [0, 8, 8, 1, 1],
       [6, 6, 9, 7, 8]])

In [62]:
m[:,4]

array([2, 9, 8, 1, 8])

In [63]:
m[0,:]

array([7, 6, 1, 4, 2])

# Alt küme üzerinde işlem yapmak 

In [66]:
a = np.random.randint(10, size = (5,5))
a

array([[7, 8, 2, 6, 7],
       [3, 7, 6, 9, 4],
       [7, 2, 4, 7, 7],
       [3, 8, 0, 6, 3],
       [5, 2, 9, 7, 3]])

In [67]:
alt_a = a[0:3,0:2]
alt_a

array([[7, 8],
       [3, 7],
       [7, 2]])

In [69]:
alt_a[0,0] = 7777
alt_a[1,1] = 1111

In [70]:
alt_a

array([[7777,    8],
       [   3, 1111],
       [   7,    2]])

In [71]:
a

array([[7777,    8,    2,    6,    7],
       [   3, 1111,    6,    9,    4],
       [   7,    2,    4,    7,    7],
       [   3,    8,    0,    6,    3],
       [   5,    2,    9,    7,    3]])

In [ ]:
# buradaki önemli nokta alt kümelerde işlem yaparken toplam kümeyi etkilemesi.

In [72]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 2, 7, 6, 9],
       [4, 8, 8, 8, 1],
       [2, 2, 1, 1, 4],
       [6, 8, 8, 7, 8],
       [7, 3, 6, 5, 2]])

In [74]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[0, 2],
       [4, 8],
       [2, 2]])

In [75]:
alt_b[0,0] = 7777

In [76]:
alt_b

array([[7777,    2],
       [   4,    8],
       [   2,    2]])

In [77]:
m

array([[0, 2, 7, 6, 9],
       [4, 8, 8, 8, 1],
       [2, 2, 1, 1, 4],
       [6, 8, 8, 7, 8],
       [7, 3, 6, 5, 2]])

In [ ]:
# görüldüğü gibi copy işlemi ana kümeden bağımsız işlem yaptırır.

# Fancy ile İndex Elemanlarına Erişmek

In [2]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
al_getir = [5,6,7]

In [7]:
v[al_getir]
# görüldüğü gibi v listesinden belirtilen dosyaları çekmek için fancy index kullanımı

array([15, 18, 21])

In [ ]:
# iki boyutta fancy index kullanımı

In [9]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [11]:
m[satir,sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [12]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
m[0, [1,2]]

array([1, 2])

In [16]:
# scile ile fancy

In [15]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [17]:
v = np.array([1,2,3,4,5])

In [18]:
v > 5

array([False, False, False, False, False])

In [19]:
v[v<5]

array([1, 2, 3, 4])

In [20]:
v[v==5]

array([5])

In [21]:
v[v!=5]

array([1, 2, 3, 4])

# Matematiksel İşlemler 

In [ ]:
# ufunc

In [22]:
v - 1 

array([0, 1, 2, 3, 4])

In [23]:
v * 10

array([10, 20, 30, 40, 50])

In [24]:
v / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [26]:
v*10/5 -1

array([1., 3., 5., 7., 9.])

In [27]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [28]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [29]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [30]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [31]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [32]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [33]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [34]:
np.absolute(np.array([-3]))

array([3])

In [35]:
np.sin(360)

0.9589157234143065

In [36]:
np.cos(360)

-0.2836910914865273

In [37]:
v = np.array([1,2,3])

In [38]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [40]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [41]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [42]:
#cheat sheet googleda arama yapmak için çok önemli

# Numpy ile İki Bilinmeyenli Denklem Çözümü

**5*x0 + x1 = 12**

**x0 + 3*x1 = 10**

In [44]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [46]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])